# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GearWalker's wonderland
email: gearwalker@engineer.com
description: > # this means to ignore newlines until "baseurl:"
  GearWalker, he's a highly motivated computer engineer who specialize in software, hardware and computer
  game development. Interested in using technology for solving problems in funny ways.
  Want to drive world with technology by a tons of knowledge and experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gearwalker.com" # the base hostname & protocol for your site
twitter_username: gearwalker
github_username:  gearwalker

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman